# Generated by Django 5.0.3 on 2024-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0003_estudiante_instructor_curso_destacado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
