# Generated by Django 5.0.3 on 2024-03-27 23:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0004_alter_curso_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="curso",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("borrador", "Borrador"),
                    ("publicado", "Publicado"),
                    ("archivado", "Archivado"),
                ],
                default="Publicado",
                help_text="Los estados de curso pueden ser: Borrador, Publicado o Archivado",
                max_length=20,
            ),
        ),
    ]
