# Generated by Django 5.0.3 on 2024-03-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0005_alter_curso_categoria_alter_curso_duracion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.estudiante",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="estudiantes",
            field=models.ManyToManyField(
                through="cursos.Inscripcion", to="cursos.estudiante"
            ),
        ),
    ]
