# Generated by Django 5.0.3 on 2024-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0006_inscripcion_curso_estudiantes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "curso"), name="unique_inscripcion"
            ),
        ),
    ]
