# Generated by Django 5.0.3 on 2024-04-06 01:17

import cursos.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0007_inscripcion_unique_inscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                validators=[
                    cursos.models.duracion_minima,
                    cursos.models.duracion_maxima,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="precio",
            field=models.IntegerField(validators=[cursos.models.precio_positivo]),
        ),
    ]
