# Generated by Django 5.0.3 on 2024-04-10 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0009_alter_curso_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="is_deleted",
        ),
    ]
