# Generated by Django 5.0.3 on 2024-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0010_remove_curso_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="imagen",
            field=models.ImageField(
                blank=True, default="cursos/fallback.png", upload_to="cursos"
            ),
        ),
    ]
