# Generated by Django 5.0.3 on 2024-04-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0011_curso_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="cursos/estudiante/fallback.png",
                upload_to="cursos/estudiante",
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="cursos/instructor/fallback.png",
                upload_to="cursos/instructor",
            ),
        ),
    ]
